# ----
# Site

title: IntelliJ Platform UI Guidelines
#url: "https://long-pig.cloudvent.net"
baseurl: /ui
google_analytics_key:
show_full_navigation: true
markdown: kramdown

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag).
#Add metadata tags for search engines and social networks to better index and display your site's content.
logo: /logo_JetBrains_4.svg


permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
